### ISSUE TITLE
Edit gtk.css for colored headerbar titlebar: not working for terminal and GTK2 apps

### ISSUE THREAD

**Issue by Trikenstein** [EliverLara/Otis#1]
Hi,

I know that this is not officially supported by the theme design. But would appreciate if you can help to fix. I am an old fashion person. And I have a monitor which can display colors. Somehow, I distinguish better the windows when there is a colored titlebar. If I add the this code at the bottom of `gtk-3.0/gtk.css` 

```css
.titlebar, headerbar {
  background-color: #983b88;
}
.titlebar:backdrop, headerbar:backdrop {
  background-color: #632659;
}
```

This works almost OK. Except that the Gnome terminal and GTK2 apps still have the dark color titlebar. Doing the same `gtk.css` modification on your other themes (Nord and Juno) there is no such problem.

Hope the fix is not too complicate. Thanks.
